
#=====================================================
# VERBOSITY
#=====================================================

/control/execute mac/verbose.mac

#=====================================================
# VISUALISATION
#=====================================================

/control/execute mac/visu.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# World
/gate/world/geometry/setXLength 1 m
/gate/world/geometry/setYLength 1 m
/gate/world/geometry/setZLength 5 m
/gate/world/setMaterial Air


# Water Box
/gate/world/daughters/name              waterbox
/gate/world/daughters/insert            box
/gate/waterbox/geometry/setXLength      40 cm
/gate/waterbox/geometry/setYLength      40 cm
/gate/waterbox/geometry/setZLength      400 cm
/gate/waterbox/placement/setTranslation 0 0 0 cm
/gate/waterbox/setMaterial ScintX
/gate/waterbox/vis/setVisible 1
/gate/waterbox/vis/setColor blue

#=====================================================
# PHYSICS
#=====================================================

#/gate/physics/addProcess PhotoElectric
#/gate/physics/processes/PhotoElectric/setModel StandardModel

#/gate/physics/addProcess Compton
#/gate/physics/processes/Compton/setModel PenelopeModel

#/gate/physics/addProcess RayleighScattering
#/gate/physics/processes/RayleighScattering/setModel PenelopeModel

#/gate/physics/addProcess ElectronIonisation
#/gate/physics/processes/ElectronIonisation/setModel StandardModel e-

#/gate/physics/addProcess Bremsstrahlung
#/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-

#/gate/physics/addProcess MultipleScattering e-

/gate/physics/addPhysicsList emstandard_opt1
/gate/physics/addPhysicsList QBBC


#/gate/physics/processList Enabled
#/gate/physics/processList Initialized

/gate/physics/Gamma/SetCutInRegion      world 10 mm
/gate/physics/Electron/SetCutInRegion   world 10 mm
/gate/physics/Positron/SetCutInRegion   world 10 mm

/gate/physics/Gamma/SetCutInRegion      waterbox 0.1 mm
/gate/physics/Electron/SetCutInRegion   waterbox 0.1 mm
/gate/physics/Positron/SetCutInRegion   waterbox 0.1 mm

/gate/physics/displayCuts


#=====================================================
# DETECTORS
#=====================================================

/gate/actor/addActor                        DoseActor  depthdose
/gate/actor/depthdose/save output/E10_ScintX_depth_dose.txt
/gate/actor/depthdose/attachTo            waterbox
/gate/actor/depthdose/stepHitType           random
/gate/actor/depthdose/setPosition           0 0 0 cm
/gate/actor/depthdose/setResolution         1 1 200
/gate/actor/depthdose/saveEveryNSeconds     60
/gate/actor/depthdose/enableEdep            false
/gate/actor/depthdose/enableUncertaintyEdep false
/gate/actor/depthdose/enableDose            true
/gate/actor/depthdose/normaliseDoseToMax    true
/gate/actor/depthdose/enableUncertaintyDose false
/gate/actor/depthdose/enableNumberOfHits    false

# I'm not insterested in the doseprofile at all so I'm not using it.

/gate/actor/addActor                          DoseActor  doseprofile
/gate/actor/doseprofile/save output/E10_ScintX_profile_dose.txt
/gate/actor/doseprofile/attachTo    	        waterbox
/gate/actor/doseprofile/stepHitType           random
/gate/actor/doseprofile/setPosition           0 0 0 cm
/gate/actor/doseprofile/setResolution         1000 1 1
/gate/actor/doseprofile/setSize               5 40 40 cm
/gate/actor/doseprofile/save output/E10_ScintX_profile_dose.txt
/gate/actor/doseprofile/enableEdep            true
/gate/actor/doseprofile/enableUncertaintyEdep true
/gate/actor/doseprofile/enableDose            false
/gate/actor/doseprofile/enableUncertaintyDose false
/gate/actor/doseprofile/enableNumberOfHits    false

#/gate/actor/addActor               SimulationStatisticActor stat
#/gate/actor/stat/save              output/gamma-stat.txt
#/gate/actor/stat/saveEveryNSeconds 60


#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize


#=====================================================
# BEAMS
#=====================================================

/gate/source/addSource mybeam gps
/gate/source/mybeam/gps/particle gamma
/gate/source/mybeam/gps/pos/type Beam
/gate/source/mybeam/gps/pos/rot1 0 1 0
/gate/source/mybeam/gps/pos/rot2 1 0 0
/gate/source/mybeam/gps/pos/shape Circle
/gate/source/mybeam/gps/pos/centre 0 0 -210 cm
/gate/source/mybeam/gps/pos/sigma_x 3 mm
/gate/source/mybeam/gps/pos/sigma_y 3 mm
/gate/source/mybeam/gps/ene/mono 10 MeV
/gate/source/mybeam/gps/ene/type Gauss
/gate/source/mybeam/gps/ene/sigma 1.0 eV
/gate/source/mybeam/gps/direction 0 0 1

#=====================================================
# START BEAMS
#=====================================================

# JamesRandom Ranlux64 MersenneTwister
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

#/tracking/verbose 1

/gate/application/noGlobalOutput
/gate/application/setTotalNumberOfPrimaries 10000000
/gate/application/start
